title: Kellie Cobb # your name (or website title) here
logo: "https://github.com/kelliecobb/kelliecobb/blob/master/Kellie%20head%20shot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seeking electrical engineering internship opportunities as a student excited by challenge, diligent in striving for excellence, and adept at critical thinking. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/kellie-cobb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
