title: Kellie Cobb # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Electrical engineering student excited by challenge, diligent in striving for excellence, and adept at critical thinking. 
  <br><br>
  --
  Since attending Bellevue College as a Running Start student in high school, I have been fascinated by the way math describes the way the world works. 
  Since attending Seattle Pacific University as an electrical engineering student, I have been captivated by the way math can be applied to create functioning systems and devices.
  One day, I hope to make the world a better place by creatively solving problems through software and hardware design.
  <br><br>
  
  <a href="https://www.linkedin.com/in/kellie-cobb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
